config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles

  resources :writers

  get "sections/:name" => "section#show", as: :section
  root to: 'users#index'


end

app/models/article.rb
class Article < ApplicationRecord
  #attr_accessible :section, :writer, :title, :content

  belongs_to :section
  belongs_to :writer

  validates :content, presence: true
  validates :title, presence: true, uniqueness: true

  def snippet
    content[0, 77] + "..."
  end  

  has_one_attached :avatar
  validates :avatar, presence:true
  


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    #@article.avatar.attach(params[:avatar])
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private

  def article_params
    params.require(:article).permit(:title,:content,:section_id,:writer_id,:avatar)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>


  <div class="field">
    <%= f.label :Wirte %><br />
    <%= f.text_field :writer_id %>
  </div>


  <div class="field">
    <%= f.label :section %><br />
    <%= f.text_field :section_id %>
  </div> 


  <div class="field">
    <%= f.label :image%><br />
    <%= f.file_field :avatar %>
  </div> 
        
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h2>All Articles</h2>

<table>
  <tr>
    <th>Section</th>
    <th>Title</th>
    <th>Writer</th>
    <th>Content</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td class="section-link">
        <%= link_to article.section.name, article.section %>
      </td>
      <td class="article-title">
        <%= link_to article.title, article %>
      </td>
      <td class="writer-link">
        <%= link_to article.writer.name, article.writer %>
      <td class="article-snippet"><%= article.snippet %></td>
    </tr>
  <% end %>


  <%= link_to 'New Articles ', new_article_path %> 

</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<h3><%= @article.writer.name %></h3>
<div class="article-body">
  <% @article.content.each_line do |paragraph| %>
    <p><%= paragraph %></p>
  <% end %>




</div>