config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles

  resources :writers

  get "sections/:name" => "section#show", as: :section
  root to: 'users#index'


end

app/models/writer.rb
class Writer < ApplicationRecord
  #attr_accessible :email, :name, :articles, :section
  has_many :articles
  has_one :section
  validates :name, :email, presence: true, uniqueness: true  
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  # GET /writers
  # GET /writers.json
  def index
    @writers = Writer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @writers }
    end
  end

  # GET /writers/1
  # GET /writers/1.json
  def show
    @writer = Writer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @writer }
    end
  end

  # GET /writers/new
  # GET /writers/new.json
  def new
    @writer = Writer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @writer }
    end
  end

  # GET /writers/1/edit
  def edit
    @writer = Writer.find(params[:id])
  end

  # POST /writers
  # POST /writers.json
  def create
    @writer = Writer.new(writer_params)

    respond_to do |format|
      if @writer.save
        format.html { redirect_to @writer, notice: 'Writer was successfully created.' }
        format.json { render json: @writer, status: :created, location: @writer }
      else
        format.html { render action: "new" }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /writers/1
  # PUT /writers/1.json
  def update
    @writer = Writer.find(params[:id])

    respond_to do |format|
      if @writer.update(writer_params)
        format.html { redirect_to @writer, notice: 'Writer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1
  # DELETE /writers/1.json
  def destroy
    @writer = Writer.find(params[:id])
    @writer.destroy

    respond_to do |format|
      format.html { redirect_to writers_url }
      format.json { head :no_content }
    end
  end

  private

  def writer_params
    params.require(:writer).permit(:name,:email)
  end
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/writers/_form.html.erb
<%= form_for(@writer) do |f| %>
  <% if @writer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@writer.errors.count, "error") %> prohibited this writer from being saved:</h2>

      <ul>
      <% @writer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/writers/edit.html.erb
<h1>Editing writer</h1>

<%= render 'form' %>

<%= link_to 'Show', @writer %> |
<%= link_to 'Back', writers_path %>

app/views/writers/index.html.erb
<h1>Listing writers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @writers.each do |writer| %>
  <tr>
    <td><%= writer.name %></td>
    <td><%= writer.email %></td>
    <td><%= link_to 'Show', writer %></td>
    <td><%= link_to 'Edit', edit_writer_path(writer) %></td>
    <td><%= link_to 'Destroy', writer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Writer', new_writer_path %>

app/views/writers/new.html.erb
<h1>New writer</h1>

<%= render 'form' %>

<%= link_to 'Back', writers_path %>

app/views/writers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @writer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @writer.email %>
</p>


<%= link_to 'Edit', edit_writer_path(@writer) %> |
<%= link_to 'Back', writers_path %>